direction: right

Dashboards: {
  Frontend: {
    CustomerDashboard
    AdminDashboard
  }

  Backend: {
    DatabaseManager
  }
}

Database: {
  DashboardDatabase: {
    shape: cylinder
    DashboardUserProfiles
    UserPreferences
    Jobs
  }
  ContentDatabase: {
    shape: cylinder
    UserTikTokCredentials
    MediaAssets
  }
}

Backend: {
  ContentLayer: {
    ContentGeneratorService
    ContentPostingService
    ContentScrapingService
    ContentSchedulingService
    DatabaseManager
  }
  API
  TaskService: {
    Temporal
  }
}

Dashboards.Frontend -> Dashboards.Backend: "Interacts with"
Dashboards.Backend -> Backend.API
Dashboards.Backend.DatabaseManager -> Database.DashboardDatabase
Backend.API -> Backend.ContentLayer
Backend.ContentLayer -> Backend.TaskService
Backend.ContentLayer.DatabaseManager -> Database.ContentDatabase
