Frontend: {
  Customer Dashboard
  Admin Dashboard
}

Database: {
  shape: cylinder
  DashboardDatabase: {
    Dashboard User Profiles
    User Preference
  }
  UserTikTokCredentials
}


Backend: {
    Content Generator
    Content Posting Service
    Reddit Story Scraping
}

Frontend -> Backend
Frontend -> Database.DashboardDatabase
Backend -> Database.UserTikTokCredentials