name: Build Image

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Buildx
        uses: docker/setup-build-action@v4
      - name: Build
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: app:test
