name: Run Go Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Test
        run: cd incubator && go test ./...